### ISSUE TITLE
env: node\r: No such file or directory 

### ISSUE THREAD

**Issue by bartzilla** [smallstack/smallstack-cli#1]
After updating the latest smallstack-cli running on mac os 10.11.6 the following error occurs.

`env: node\r: No such file or directory`

Temporary solution I found. Convert the smallstack file to unix format.
- `brew install dos2unix`
- `sudo dos2unix /usr/local/lib/node_modules/smallstack-cli/bin/smallstack`

or just follow the instructions in this link:
https://github.com/nwjs/nw-builder/issues/75

**Comment by maxfriedmann** [comment]
fixed in v0.3.5, can you verify that @bartzilla & @TimoKaiser ?
